### ISSUE TITLE
Update layout of package?

### ISSUE THREAD

**Issue by cwfink** [berkeleycdms/QETpy#11]
Should we change the way the package is structured?

**Comment by slwatkins** [comment]
QETpy's layout has been changed by @cwfink, so I would say we can close this issue.

**Comment by slwatkins** [comment]
Reopened this to add that as a part of commit fe03733d8d09047e142618b4e7436ebd5ad6e264, QETpy was once again reorganized. This should be the last major reorganization of the package.

Closing once again.
